# Header
menu:
  Home: /
  Archives: /archives
  About: /about

# Show more
excerpt_link: Read More

# Show photo
fancybox: true

# Miscellaneous
favicon: /favicon.png

# Social accounts
github: liupenglsm
weibo: liupenglsm
rss: /atom.xml