# Header
menu:
  Home: /
  Archives: /archives
  About: /about

# Content
excerpt_link: Read More
fancybox: true

# Miscellaneous
google_analytics: true
favicon: /favicon.png

# Social accounts
github: liupenglsm
weibo: liupenglsm
rss: /atom.xml